### ISSUE TITLE
Learn eagle cad

### ISSUE THREAD

**Issue by JoshuaBThompson** [JoshuaBThompson/JEM#2]
Download [eagle cad](https://cadsoft.io/) (free version)
Design / manufacture simple test pcb using [oshpark](https://oshpark.com/)

**Comment by MarkJungMoore** [comment]
Sounds good!

**Comment by JoshuaBThompson** [comment]
Good [tutorial](https://learn.sparkfun.com/tutorials/using-eagle-schematic) for designing with eagle cad
